/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:6ba9df14-3b8b-4726-88c7-6f545c70f1bc",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_6ZClWj1i0",
    "aws_user_pools_web_client_id": "2p0549i98pn6ga20k4boa0f3me",
    "oauth": {
        "domain": "ctest82f85821-82f85821-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
